### ISSUE TITLE
Behavior hell

### ISSUE THREAD

**Issue by marcalj** [creatoro/jelly#74] opened 2011-08-25 22:01 UTC
Hi, I was finding a solution to a common problem.

When updating a model I need to always do actions for sanitizing data, for example in a model "Address" I need to update the geoposition string field based on street, country, etc... before save action.

Ok, I was thinking first in a rule callback, but I think it's not the right solution, I want to change model data, not just say true/false. Also filters come to game, but I don't know if now are usable...

So, I saw in the code that Jelly supports events. I was investigating and finally... I saw Behaviors.

I can create a custom behavior for the "Address" model. This doesn't work: `classes/jelly/behavior/address.php`

``` php
class Jelly_Behavior_Address extends Jelly_Behavior {

    public function model_before_save($a)
    {
        Kohana::$log->add('debug', Debug::vars($this));
        Kohana::$log->add('debug', Debug::vars($a));
    }

}
```

If I set it up in the model `initialize` function like this: `$meta->behaviors(array('Jelly_Behavior_Address'));` doesn't work also. Error: `Call to a member function initialize() on a non-object` on `MODPATH/kohana-jelly-4995eb5/classes/jelly/core/meta.php [ 151 ]`.

Problems:
- How to setup a filter like "trim" in a model field? (well, generic way to modify data before setting it to model)
- How can I create a custom behavior
- Which are the params of the behavior functions.

Thanks.

**Comment by marcalj** [comment] 2011-08-25 22:08
More info from @banks at https://github.com/jonathangeiger/kohana-jelly/issues/133#issuecomment-315333

I don't understand the part of:

> Behaviors allow you to add functionality to model instances (as well as model builders) in such a way that multiple inheritance is achievable.
> For example, I may write several different models that all share some functionality such as maintaining a published/unpublished status. Rather than duplicate all the fields/code for handling this status, I may just create a behaviour call `Jelly_Behavior_Publishable` which adds functions to the instance like `is_published()` or `publish_now()`

**Comment by leth** [comment] 2011-08-26 10:40
From looking at the code in the meta class, can you try this:

```
$meta->behaviors(array('Address'));
```

Edit: Ignore that.

Your behaviour class is missing an initialize method.

Edit: ignore that too.

**Comment by leth** [comment] 2011-08-26 10:59
Try this:

```
$meta->behaviors(array('address' => Jelly::behavior('Address')));
```

I've added some error checking to the code in my fork of 3.1/develop so if someone does this wrong in future they should be able to work out what's going on.

**Comment by smgladkovskiy** [comment] 2011-08-26 12:45
In docs that, please! In docs before it gone! :)

**Comment by creatoro** [comment] 2011-08-30 15:36
@marcalj: check out the guide on how to apply filters. Docs will be updated soon with description about behaviors.

@leth: merged your work, thanks!

**Closed as completed by creatoro** 2011-08-30 15:36 UTC
Labels: Non-Issue, 3.1 branch

**Comment by marcalj** [comment] 2011-08-30 15:52
Sorry I made tests with creatoro branch, not @leth branch :P

Now auto-loading works, but when the event is triggered I get this log error: `ERROR: Kohana_Exception [ 0 ]: Behavior at index [ 0 ] is not an instance of Jelly_Behavior, string found. ~ MODPATH/kohana-jelly-5ae46e8/classes/jelly/core/meta.php [ 151 ]`

If I use: `$meta->behaviors(array('address' => Jelly::behavior('Address')));` the same error is thrown

I think it's more logical to put behaviors in **model** folder, like custom bulders, to get more polish in directory structure.

**Comment by creatoro** [comment] 2011-08-30 15:59
@marcalj: where did you put your behavior?

Also, try to use this branch.

**Comment by marcalj** [comment] 2011-08-30 16:02
In: `application/classes/jelly/behavior/address.php`.

``` php
<?php defined('SYSPATH') or die('No direct script access.');

class Jelly_Behavior_Address extends Jelly_Behavior {

    public function model_before_save($a)
    {
        Kohana::$log->add('debug', Debug::vars($this));
        Kohana::$log->add('debug', Debug::vars($a));
    }
    public function model_after_save($a)
    {
        Kohana::$log->add('debug', Debug::vars($this));
        Kohana::$log->add('debug', Debug::vars($a));
    }

}
```

**NOTE:** I used your updated branch.

**Comment by creatoro** [comment] 2011-08-30 16:11
I'm using the same code as you without problems. Didn't you leave a `behaviors()` call somewhere else in your model?

**Comment by marcalj** [comment] 2011-08-30 16:16
I don't found any reference in my code. I'm using your updated branch with Kohana v3.1.3.1.

Really I'm using a custom module for my app. So I have two files:

`class Jelly_Behavior_Address extends Yournet_Jelly_Behavior_Address {}`
`class Yournet_Jelly_Behavior_Address extends Jelly_Behavior {` with the code.

But I've made the checks with the first file as you could do. It's strange :S

**Comment by creatoro** [comment] 2011-08-30 16:19
Can you paste your model into a gist?

**Comment by creatoro** [comment] 2011-08-30 16:31
You can delete it.
Edit: there's nothing related to behaviors in your model.

**Comment by marcalj** [comment] 2011-08-30 16:42
I'm using auto-detection, like custom builders. Should be any reference to behaviors in Model code?

**Comment by creatoro** [comment] 2011-08-30 16:50
No, there shouldn't be, just missed when you wrote you are auto-loading it.

I can't reproduce your issue, did everything the same like you and it's working fine.

**Comment by marcalj** [comment] 2011-08-30 16:55
Mmm ok, so when you create and save an Address model, the `model_before_save` function of the Behavior is called correctly?

Well, I will use a new installation with the minimal code to test it without any references to custom classes, and I will try to check the bug. I'll notice here.

Thanks for your efforts.

**Comment by creatoro** [comment] 2011-08-30 17:09
Copy-pasted your code, used the classnames and structure you did, and it's working.

**Comment by marcalj** [comment] 2011-08-30 21:07
WTF it works perfect! You need to use one of the `Log` constants in the `Kohana::$log->add` function to work!

Ok so, I see that the first param of the event functions is the Jelly model object.

We need to be careful to not use `save()` there and also, I used to set `belongsto` field as an integer, so If I need to access this relation I use this:

``` php
        if (is_int($item->company))
        {
            $item->company = Jelly::query('company', $item->company)->select();
        }
```

So finally, the code will be:

``` php
class Jelly_Behavior_Address extends Jelly_Behavior {

    public function model_before_save($item)
    {
        if (is_int($item->company))
        {
            $item->company = Jelly::query('company', $item->company)->select();
        }

        $street = explode(',', $item->street, 2);

        $item->geoposition = array_shift($street).', '.$item->city.', '.$item->zip.', '.$item->company->country->name();
    }

}
```

Is this a correct solution? Thanks!

**Comment by creatoro** [comment] 2011-08-30 22:51
@leth, @smgladkovskiy, @marcalj: guys, I have added docs for behaviors. I was in a hurry, so I would appreciate if you could take a look.

@marcalj: glad you sorted out. You don't need to issue a select statement to access a relationship, it'll be autmatically selected if you access the relation by `$item->company`.

**Comment by marcalj** [comment] 2011-08-31 16:25
@creatoro It works! Ok, I will take a look to docs.

Jelly is awesome! :D

**Comment by marcalj** [comment] 2011-08-31 16:50
I think there's an error in the @banks quote. When he said "but could also add functions to the builder like published(TRUE)", wrote this way you can think that you can add functions to some builder using the custom behavior class. Clarification will be perfect.

Also in the built-in events I think it's better to write directly the name of the params, not using just `$params`.

For example:
`model_before_validate($model_object, $validation)`

``` model_before_save($model_object)```
```
